// Constants used across the app.
// Dead exports removed: PUTER_WORKER_URL, STORAGE_PATHS, ROOMIFY_RENDER_PROMPT,
// GRID_OVERLAY_SIZE, GRID_COLOR, PROGRESS_INCREMENT, PROGRESS_STEP, PROGRESS_INTERVAL_MS

export const SHARE_STATUS_RESET_DELAY_MS = 1500;
export const REDIRECT_DELAY_MS           = 600;
export const UNAUTHORIZED_STATUSES       = [401, 403];
export const IMAGE_RENDER_DIMENSION      = 1024;
